# -*- coding: utf-8 -*-
"""oops1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eYqM_Iux19kZ71YB-7GgUB16HubAsHZx
"""

class Employee:
  def __init__(self, emp_name, emp_id, salary):
    self.emp_name = emp_name
    self.emp_id = emp_id
    self.salary = salary
  def show_employee(self):
    print(self.emp_name,self.emp_id,self.salary)
class Course():
  def __init__(self,course_id,course_name,course_duration):
    self.course_id = course_id
    self.course_name = course_name
    self.course_duration = course_duration
  def show_course(self):
    print(self.course_id,self.course_name,self.course_duration)
obj=Employee("Laxmi",50,30000)
print(obj.__dict__)
obj1=Course(548,"Python",45)
print(obj1.__dict__)
class Feedback():
  def __init__(self,rating,comment):
    self.rating = rating
    self.comment = comment
    print=input("enter rating in[1-5]:")
    print=input("enter comment:")
obj2=Feedback(rating,comment)
print(obj2.__dict__)

class Employee:
  def __init__(self,employee_id,employee_name):
     self.employee_id=employee_id
     self.employee_name=employee_name
  def emp(self):
      print(self.employee_id)
      print(self.employee_name)


class JuniorEngineer(Employee):
  def __init__(self,employee_name,employee_id,assessement_score,feedback):
     super().__init__(employee_name,employee_id)
     self.assessement_score = assessement_score
     self.feedback = feedback
  def display(self):
      print(self.assessement_score)
      print(self.feedback)
class SoftwareEngineer(Employee):
  def __init__(self,employee_name,employee_id,project_name):
     super().__init__(employee_name,employee_id)
     self.project_name = project_name
  def show(self):
      print(self.project_name)
class Trainer(Employee):
  def __init__(self,employee_name,employee_id,skills,certifications):
      super().__init__(employee_name,employee_id)
      self.skills = skills
      self.certifications = certifications
  def show1(self):
       print(self.skills)
       print(self.certifications)
junior = JuniorEngineer(101, "Lakshmi", 95, "Good")
print(junior.__dict__)
software = SoftwareEngineer(102, "Rahul", "AI Resume Builder")
print(software.__dict__)
trainer = Trainer(103, "Anu","Python", "AWS")
print(trainer.__dict__)
print("junioregineer")
junior.display()
print("software")
software.show()
print("trainer")
trainer.show1()