# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GvfFGktZyYLm4cWrbcCoizIjbvfLVasy
"""

n=6
for outer_loop in range(1,n+1):
    for spaces in range(outer_loop-1):
        print("",end="")
    for stars in range(n-outer_loop+1):
        print("*",end="")
    print()



n=6
for outer_loop in range(1,n+1):
    for spaces in range(outer_loop-1):
        print("",end="")
    for stars in range(outer_loop):
        print("*",end="")
    print()



n=6
for outer_loop in range(n+1):
    for spaces in range(n-1):
        print("",end="")
    for stars in range(outer_loop):
        print("*",end="")
    print()

n=6
for outer_loop in range(n,0,-1):
    for spaces in range(n-1):
        print("",end="")
    for stars in range(outer_loop):
        print("*",end="")
    print()

rows=5
for outer in range(rows):
  for inner in range(rows):
    if outer==0 or outer==rows-1 or inner==0 or inner==rows-1:
      print("*",end="")
    else:
      print(" ",end="")
  print()

try:
 account_balance=int(input("enter balance"))
 withdraw_amount=int(input("enter withdrawn amount"))
 if withdraw_amount==0:
    raise account("please enter an amount greater then zero")
 elif withdraw_amount>account_balance:
    raise ValueError("insufficnt balance in your account")
 else:
    print(account_balance-withdraw_amount)
except valueError as e:
   print(f"valueerror:{e}")
finally:
    print("thank you for using an ATM")